### ISSUE TITLE
bad declarer play

### ISSUE THREAD

**Issue by seebrand** [lorserker/ben#142] opened 2024-04-28 14:21 UTC
![image](https://github.com/lorserker/ben/assets/32126008/3c1b0c18-8187-40d8-80c6-d3af63fd129c)
lead CQ,  set  6h -1 .  Ben let south ruff s before clear drump。that‘s poor ！

**Comment by seebrand** [comment] 2024-04-28 14:24
lead CQ，not s7.

**Comment by ThorvaldAagaard** [comment] 2024-04-28 14:26
Did you play it locally? Then please paste the boards as text or BBA code, so I can replay it

**Comment by seebrand** [comment] 2024-04-28 15:10
http://localhost:8080/app/bridge.html?deal=(%27J65432.Q.KJ4.953%20K98.AKJ532.6.A64%207.976.QT872.QJT7%20AQT.T84.A953.K82%27,%20%27N%20N-S%27)&P=1&board_no=341&A=x&T=2

**Comment by seebrand** [comment] 2024-04-28 15:12
Ben auto lead s7,then mk. if S lead cQ, -1.

**Comment by seebrand** [comment] 2024-04-28 15:21
![image](https://github.com/lorserker/ben/assets/32126008/fd2c110e-a6cf-4552-abbd-1465665b4200)

**Comment by ThorvaldAagaard** [comment] 2024-04-28 15:22
I assume BEN found some constraints, that confused PIMC, and will look into it.
Did you use the default settings?

**Comment by seebrand** [comment] 2024-04-28 15:32
yes. use latest verson.

**Comment by ThorvaldAagaard** [comment] 2024-04-28 15:56
I think this was caused by having to much trust in the NN. That has now been removed, and BEN makes 6H on lead of the CQ.
Please try and close this issue, if it now is OK

**Comment by seebrand** [comment] 2024-04-29 15:13
now is ok. Ben drop last drump after SK. it's not safe anyway . why Ben do not clear drump at first?

**Comment by ThorvaldAagaard** [comment] 2024-04-29 15:24
Neural network did not suggest to remove the last trump, now double dummy decides.

**Closed by ThorvaldAagaard** 2024-04-29 15:24 UTC
